steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'VITE_API_URL=${_VITE_API_URL}'
      - '-t'
      - '${_IMAGE_TAG}'
      - '.'

images:
  - '${_IMAGE_TAG}'

substitutions:
  _VITE_API_URL: 'http://localhost:8000'
  _IMAGE_TAG: 'asia-southeast1-docker.pkg.dev/PROJECT_ID/smart-english/frontend:latest'
